[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Epigenetics"
authors = [{name = "Joseph", email = "joseph.kirangwa@bioch.ox.ac.uk"}]
dynamic = ["version", "description"]
